name: Run PGEdge SBOM Action

on:
  workflow_dispatch:

jobs:
  sbom-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Run SBOM Action for PG17
        uses: maqeel75/pgedge-sbom-action@v1.0.0
        with:
          pg_tarball_url: https://pgedge-download.s3.amazonaws.com/REPO/pg17-17.5-1-amd.tgz

      - name: Debug output files
        run: |
          echo "📂 Contents of pg_sbom:"
          ls -lhR ./pg_sbom

      - name: Upload SBOM and Reports
        uses: actions/upload-artifact@v4
        with:
          name: pg17-sbom-artifacts
          path: ./pg_sbom

      - name: Run SBOM Action for etcd
        uses: maqeel75/pgedge-sbom-action@v1.0.0
        with:
          pg_tarball_url: https://pgedge-download.s3.amazonaws.com/REPO/etcd-3.5.12-2-amd.tgz

      - name: Debug output files
        run: |
          echo "📂 Contents of pg_sbom:"
          ls -lhR ./pg_sbom

      - name: Upload SBOM and Reports
        uses: actions/upload-artifact@v4
        with:
          name: etcd-sbom-artifacts
          path: ./pg_sbom

      - name: Run SBOM Action for spock40-pg17
        uses: maqeel75/pgedge-sbom-action@v1.0.0
        with:
          pg_tarball_url: https://pgedge-download.s3.amazonaws.com/REPO/spock40-pg17-4.0.9-1-amd.tgz

      - name: Debug output files
        run: |
          echo "📂 Contents of pg_sbom:"
          ls -lhR ./pg_sbom

      - name: Upload SBOM and Reports
        uses: actions/upload-artifact@v4
        with:
          name: spock40-pg17-sbom-artifacts
          path: ./pg_sbom

